version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_DATABASE=bitnami_opencart
      - MARIADB_USER=bn_opencart
      - MARIADB_PASSWORD=${OPENCART_DATABASE_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-mariadb_root_password}
    volumes:
      - mariadb_data:/bitnami/mariadb
  opencart:
    image: docker.io/bitnami/opencart:3.0.3-8
    ports:
      - 80:8080
      - 443:8443
    environment:
      - OPENCART_HOST=${OPENCART_HOST}
      - OPENCART_DATABASE_PASSWORD=${OPENCART_DATABASE_PASSWORD}
      - OPENCART_ENABLE_HTTPS=${OPENCART_ENABLE_HTTPS:-no}
    volumes:
      - opencart_data:/bitnami/opencart
      - opencart_storage_data:/bitnami/opencart_storage
      ## https configurations
      # - ./opencart-https-vhosts.conf:/opt/bitnami/apache2/conf/vhosts/opencart-https-vhosts.conf:ro
      ## example using exiting letsencrypt certs
      # - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
networks:
   default:
    name: opencart_network
